baseURL = "https://luett-und-satt.de/"
languageCode = "de-de"
title = "Lütt & Satt - Pragmatisches Kleinkinderessen"
theme = "PaperMod"

[params]
  description = "Schietbüdel-Kombüse: Schnelle Rezepte für die Lütten."
  mainSections = ["rezepte"]
  ShowFullTextinMain = true
  hideMeta = true
  DateFormat = "" # Macht das Datum unsichtbar
  disableThemeToggle = true
  defaultTheme = "light"
  ShowShareButtons = true
  ShareButtons = ["whatsapp", "facebook", "telegram", "x", "reddit"]
  images = ["/luett-und-satt-vorschau.png"]

[params.homeInfoParams]
  title = "Moin bei Lütt & Satt! 🥣"
  content = "Schietbüdel-Kombüse: Schnelle Rezepte für die Lütten. \n\n **Wichtiger Hinweis vorweg:** Ich bin ein kochendes Elternteil, kein Kinderarzt. Alle Rezepte haben bei uns wunderbar funktioniert, aber achtet bitte selbst auf Allergien eurer Kinder und darauf, ob sie schon so weit sind, bestimmte Konsistenzen zu kauen."


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[[menu.main]]
  identifier = "search"
  name = "Suchen & Stöbern"
  url = "/search/"
  weight = 10

[[menu.main]]
  identifier = "vorschlaege"
  name = "Vorschläge?"
  url = "/vorschlaege/"
  weight = 15

[[menu.main]]
  identifier = "kaffee"
  name = "☕ Kaffee spendieren"
  url = "https://paypal.me/janharrie/3"
  weight = 30

[params.label]
  text = "Lütt & Satt"